orbs:
  react: thefrontside/react@0.2.0
version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:10.16.0
        working_directory: ~/repo
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: npm install
            - save_cache:
                  key: v1-npm-deps-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: Build
                  command: npm build
            - run:
                  name: Firebase Deploy
                  command: /Users/bensheridanedwards/Documents/2020/Coding/Udemy-LearningReact/ReactProjects/Season_Teller_React deploy --token "$FIREBASE_TOKEN" --only hosting