orbs:
  react: thefrontside/react@0.2.0
  code-climate-quality: freighthub/code-climate-quality@0.0.4
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
      - run:
            name: Install Dependencies
            command: npm install
      - save_cache:
            key: v1-npm-deps-{{ checksum "package-lock.json" }}
            paths:
              - ./node_modules
      - run:
            name: Build Project
            command: npm run-script build
  Run Tests:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - run:
            name: Run Tests
            command: npm run-script test
  Setup Code Climate:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - run:
            name: Setup Code Climate test-reporter
            command: |
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
     
  Send Coverage Report:
    docker:
      - image: circleci/ruby:2.6.3-node
    working_directory: ~/repo
    steps:
      - run:
            name: Build, Save and Send Coverage Report to Code Climate
            command: |
              ./cc-test-reporter before-build
              npm run test:coverage
              ./cc-test-reporter after-build --debug -t lcov --exit-code $?

  Deploy to Firebase:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/repo
    steps:
      - run:           
            name: Deploy to Firebase Hosting
            command: './node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'
            description: Run tests with coverage and upload results to code climate
      

            